import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import GitHubImg from "../images/github-light.png";
import LinkedInImg from "../images/linkedin.png";
import TwitterImg from "../images/twitter-blue.png";
import UpworkImg from "../images/upwork.png";
import { trpc } from "../utils/trpc";

type TechnologyCardProps = {
  name: string;
  description: string;
  documentation: string;
};

const Home: NextPage = () => {
  const hello = trpc.useQuery(["example.hello", { text: "world!" }]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main id="main" className="grid grid-rows-6 h-screen">
        <section
          id="introduction"
          className="row-start-2 row-span-2 flex flex-col items-center justify-center"
        >
          <h1 className="text-center text-5xl m-2">
            Hi. I'm Reljod. <br />
            <span className="text-3xl">A Full Stack Developer</span>
          </h1>
          <p className="w-2/3 my-4 text-center">
            I'm a Software Engineer who builds software for fun.
          </p>
        </section>
        <div className="row-start-4 flex flex-col items-center justify-center">
          <h3 className="italic">
            &ldquo;Let's make your idea into a reality.&rdquo;
          </h3>
        </div>
        <div className="row-start-5 flex flex-col items-center justify-center">
          <h3>{"Let's connect via:"}</h3>
          <div className="flex justify-center items-center space-x-10 p-3 m-2">
            <a
              href="https://github.com/Reljod"
              target="_blank"
              rel="noreferrer"
            >
              <Image
                src={GitHubImg}
                alt="github-page"
                width="40px"
                height="35px"
              />
            </a>
            <a
              href="https://twitter.com/Dojler"
              target="_blank"
              rel="noreferrer"
            >
              <Image
                src={TwitterImg}
                alt="twitter-page"
                width="40px"
                height="35px"
              />
            </a>
            <a
              href="https://www.linkedin.com/in/reljodoreta/"
              target="_blank"
              rel="noreferrer"
            >
              <Image
                src={LinkedInImg}
                alt="linkedin-page"
                width="40px"
                height="35px"
              />
            </a>
            <a
              href="https://www.upwork.com/freelancers/~0129af27eda5b1ccd6"
              target="_blank"
              rel="noreferrer"
            >
              <Image
                src={UpworkImg}
                alt="upwork-page"
                width="40px"
                height="35px"
              />
            </a>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
